name: summit_parts
description: 'Summit Parts Mobile Application'
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.8.0+1

  # Navigation
  go_router: ^15.0.0

  # Logging
  loggy: ^2.0.3
  flutter_loggy: ^2.0.3+1
  flutter_loggy_dio: ^3.1.0

  # JSON Serialization
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.15

  # JSON Serialization
  json_serializable: ^6.9.4

  # Linting
  flutter_lints: ^5.0.0

  # Task Runner
  melos: ^7.0.0-dev.8

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500

melos:
  scripts:
    generate:
      desc: Generate code for the project
      run: dart run build_runner build --delete-conflicting-outputs
    generate-assets:
      desc: Generate code for assets
      run: fluttergen
